""" Do not change these keys unless the data structure changes """
CREATED = "created"
MISSION_TEMPL = "mission_templ"
MISSION_STATUS = "mission_status"
SUCCEEDED = "SUCCEEDED"
CANCELLED = "CANCELLED"
EXECUTION_TIME = "execution_time"
""" These keys may be changes as they are setup by us during processing and will result in different keys outputted in the report """
MISSION_COUNT = "COUNT"
MISSION_SUCCEEDED = "SUCCEEDED"
MISSION_CANCELLED = "CANCELLED"
